Public Class LocationModel
    Public Property Oid As Guid
    Public Property OrganizationName As String
    Public Property Organization As Guid?
    Public Property Name As String
    Public Property IsActive As Boolean?
    Public Property Company As Guid?
    Public Property EmailAddress As String
    Public Property PrimaryPhone As String
    Public Property Fax As String
    Public Property MobilePhone As String
    Public Property SecondaryPhone As String
    Public Property Address As String
    Public Property City As String
    Public Property State As String
    Public Property Zip As String
    Public Property LocationName As String
    Public Property WebRegionalName As String
    Public Property WebPrimaryBuildingPhoto As String
    Public Property WebMapPhoto As String
    Public Property WebTopPerformerOrder As Integer?
    Public Property Longitude As Double?
    Public Property Latitude As Double?
    Public Property isShowCalendarOnWeb As Boolean?
    Public Property IsCalendarWithBookings As Boolean?
    Public Property WebMapZoomLevel As Integer?
    Public Property SequenceId As Long?
    Public Property OutgoingUserName As String
    Public Property OutgoingServerName As String
    Public Property OutgoingPassword As String
    Public Property OutgoingServerPort As Integer?
    Public Property DBAName As String
    Public Property PrimaryEmail As String
    Public Property CalcByNights As Boolean?
    Public Property MinimumNumberOfTimeInterval As Integer?
    Public Property WebGoogleMapJavaScriptAPIKey As String
    Public Property IsLocationBehindOnPaying As Boolean?
    Public Property WebStoreHours As String
    Public Property WebQuoteEmailAddress As String
End Class
