Public Class FeaturedVehicleViewModel
    Public Property VehicleOid() As Guid
    Public Property VehicleKey() As String
    Public Property Name() As String
    Public Property Price() As String
    Public Property VehicleClass() As Guid?
    Public Property WebPriceGroup() As Double?
    Public Property VehicleSequenceId() As Long?
    Public Property Adolescents() As Integer?
    Public Property Adults() As Integer?
    Public Property Children() As Integer?
    Public Property WebCleaningFee() As Decimal?
    Public Property WebPrepFee() As Decimal?
    Public Property WebRefundableSecurityDeposit() As Decimal?
    Public Property WebGeneratorFreeHours() As Integer?
    Public Property WebGeneratorAddHoursEach() As Integer?
    Public Property WebIncludesTheseMilesFreePerDay() As Integer?
    Public Property WebMinimumNumberOfTimeInterval() As Integer?
    Public Property FeaturedVehicle() As Boolean?
    Public Property HigherRate() As Decimal?
    Public Property Make() As String
    Public Property Model() As String
    Public Property WebDescription() As String
    Public Property WebEventPriceForPickedUp() As Decimal?
    Public Property WebEventPriceForDelivered() As Decimal?
    Public Property WebEventPriceForDelivered2() As Decimal?
    Public Property WebEventDescription() As String
    Public Property WebUniqueId() As String
    Public Property InsurancePolicy() As Guid?
    Public Property Photo() As String
    Public Property ClassType() As Integer?
    Public Property ClassName() As String
    Public Property Location() As Guid?
    Public Property LocationName() As String
    Public Property WebRegionalName() As String
    Public Property CalcByNights() As Boolean?
    Public Property MinimumNumberOfTimeInterval() As Integer?
    Public Property IsLocationBehindOnPaying() As Boolean?
    Public Property WebLocationPageHTML() As String
    Public Property WebLocationPageHTMLBottom() As String
    Public Property DateList() As List(Of String)
    Public Property IsSquarePhoto() As Boolean
End Class
